name: Deploy to VPS

on:
  push:
    branches:
      - main # ou master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: docker build -t your-docker-image-name .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag your-docker-image-name your-dockerhub-username/your-docker-image-name:latest
          docker push your-dockerhub-username/your-docker-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem root@92.112.192.52 << 'EOF'
            docker pull your-dockerhub-username/your-docker-image-name:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 3000:3000 your-dockerhub-username/your-docker-image-name:latest
          EOF
