name: Deploy to VPS

on:
  push:
    branches:
      - main  # ou master selon votre workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: docker build -t djosh35/tickly-back:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag djosh35/tickly-back:${{ github.sha }} djosh35/tickly-back:latest
          docker push djosh35/tickly-back:${{ github.sha }}
          docker push djosh35/tickly-back:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Installer sshpass pour permettre l'utilisation de mots de passe avec SSH
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS using Docker Compose
        run: |
          # Connexion au VPS en utilisant sshpass
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /path/to/your/docker-compose/directory

            # Pull the latest image from Docker Hub
            docker-compose pull tickly-back

            # Stop and remove any existing containers
            docker-compose down

            # Start the services (NestJS backend and PostgreSQL)
            docker-compose up -d
          EOF
